[package]
name = "sol-vault"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.18"
borsh = "1.5.1"
borsh-derive = "1.5.1"

[features]
test-bpf = []

[lib]
crate-type = ["cdylib", "lib"]
